import { useMemo } from 'react';
import { ArrowDownRight, ArrowUpRight, BarChart3, TrendingUp } from 'lucide-react';
import { useListInstitutes, useListInspections } from '@workspace/api-client-react';
import { ErrorState, LoadingRows, MetricTile, PageFrame, Section, StatusBadge } from '@/components/command-ui';

export default function Analytics() {
  const institutesQuery = useListInstitutes();
  const inspectionsQuery = useListInspections();
  const institutes = institutesQuery.data ?? [];
  const inspections = inspectionsQuery.data ?? [];
  const distribution = useMemo(() => ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((level) => ({ level, count: institutes.filter((item) => item.riskLevel === level).length })), [institutes]);
  const error = institutesQuery.isError || inspectionsQuery.isError;
  return <PageFrame eyebrow="Decision support / 06" title="Risk analytics" description="A compact read of distribution, drift, and the deterministic inspection journey."><div className="metric-grid compact-grid"><MetricTile label="Portfolio score" value={institutes.length ? (institutes.reduce((sum, item) => sum + item.riskScore, 0) / institutes.length).toFixed(1) : '—'} note="Mean composite risk" tone="primary" /><MetricTile label="Signals observed" value={institutes.filter((item) => item.observedAttendance !== null).length} note="Of tracked institutes" /><MetricTile label="Filed findings" value={inspections.filter((item) => item.assignmentStatus === 'SUBMITTED').length} note="Submitted inspections" /></div>{error ? <Section title="Analytics unavailable"><ErrorState message="Risk signals could not be assembled." onRetry={() => { void institutesQuery.refetch(); void inspectionsQuery.refetch(); }} /></Section> : institutesQuery.isLoading || inspectionsQuery.isLoading ? <LoadingRows count={4} /> : <div className="analytics-grid"><Section title="Risk distribution" caption="Current institute portfolio"><div className="distribution">{distribution.map(({ level, count }) => <div className="distribution-row" key={level} data-testid={`metric-distribution-${level.toLowerCase()}`}><div className="distribution-label"><StatusBadge level={level} /><strong>{count}</strong></div><div className="distribution-track"><span className={level.toLowerCase()} style={{ width: `${institutes.length ? Math.max(5, count / institutes.length * 100) : 0}%` }} /></div></div>)}</div></Section><Section title="Deterministic signal journey" caption="Saksham Rehabilitation Centre / model trace"><div className="trend-chart"><div className="trend-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="trend-area"><div className="trend-grid" /><div className="trend-line"><span className="trend-point point-one"><b>42</b><small>baseline</small></span><span className="trend-point point-two"><b>81</b><small>critical</small></span><span className="trend-point point-three"><b>94</b><small>filed</small></span></div></div></div><div className="trend-legend"><span><i className="legend-dot baseline" /> Initial model score</span><span><i className="legend-dot critical" /> After monitoring</span><span><i className="legend-dot filed" /> Confirmed finding</span></div></Section><Section title="Model readout" caption="What moved the score"><div className="readout-list"><div><TrendingUp size={15} /><span>Attendance discrepancy</span><strong>52.3%</strong><ArrowUpRight size={14} /></div><div><BarChart3 size={15} /><span>Inspection escalation</span><strong>+13 pts</strong><ArrowUpRight size={14} /></div><div><ArrowDownRight size={15} /><span>Evidence state</span><strong>NON_COMPLIANT</strong><ArrowDownRight size={14} /></div></div></Section></div>}</PageFrame>;
}