import { useMemo, useState } from 'react';
import { Camera, FileCheck2, MapPin, Search } from 'lucide-react';
import { useListInspections } from '@workspace/api-client-react';
import { ErrorState, LoadingRows, PageFrame, Section, StatusBadge } from '@/components/command-ui';

export default function Evidence() {
  const query = useListInspections();
  const [selectedId, setSelectedId] = useState('');
  const [search, setSearch] = useState('');
  const records = query.data ?? [];
  const filtered = useMemo(() => records.filter((item) => `${item.institute.name} ${item.inspector} ${item.id}`.toLowerCase().includes(search.toLowerCase())), [records, search]);
  const selected = records.find((item) => item.id === selectedId) ?? filtered[0];
  return <PageFrame eyebrow="Records / 07" title="Evidence & reports" description="A traceable archive of field submissions, coordinates, and decision-ready findings."><div className="content-grid evidence-grid"><Section title="Inspection records" caption={`${filtered.length} reports`}><div className="search-field evidence-search"><Search size={15} /><input className="input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search reports" data-testid="input-evidence-search" /></div>{query.isLoading ? <LoadingRows /> : query.isError ? <ErrorState message="Evidence records could not be loaded." onRetry={() => void query.refetch()} /> : filtered.length === 0 ? <div className="empty-state" data-testid="state-empty-evidence">No reports have been filed yet.</div> : <div className="evidence-list">{filtered.map((item) => <button className={`evidence-item ${selected?.id === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelectedId(item.id)} data-testid={`button-evidence-${item.id}`}><div className="evidence-icon"><FileCheck2 size={15} /></div><div><strong>{item.institute.name}</strong><span>{item.inspector} · {item.reason}</span></div><StatusBadge level={item.assignmentStatus} /></button>)}</div>}</Section><Section title="Report detail" caption={selected ? selected.id : 'Select a report'}>{selected ? <div className="report-detail" data-testid={`detail-evidence-${selected.id}`}><div className="report-heading"><div><div className="eyebrow">Filed inspection</div><h2>{selected.institute.name}</h2><p>{selected.reason}</p></div><StatusBadge level={selected.confirmed === true ? 'NON_COMPLIANT' : selected.assignmentStatus} /></div><div className="report-grid"><div><span>Risk at assignment</span><strong>{selected.riskScore.toFixed(0)}</strong></div><div><span>Inspector</span><strong>{selected.inspector}</strong></div><div><span>Coordinates</span><strong>{selected.latitude !== null && selected.longitude !== null ? `${selected.latitude.toFixed(4)}, ${selected.longitude.toFixed(4)}` : 'Not captured'}</strong></div><div><span>Evidence</span><strong>{selected.evidence ?? 'No file reference'}</strong></div></div><div className="report-note"><div className="eyebrow">Field notes</div><p>{selected.notes ?? 'No notes were attached to this report.'}</p></div><div className="evidence-stamp"><Camera size={15} /><span>{selected.evidence ? 'Evidence reference attached' : 'Evidence reference pending'}</span><MapPin size={15} /><span>{selected.latitude !== null ? 'GPS captured' : 'GPS not captured'}</span></div></div> : <div className="empty-state" data-testid="state-empty-report-detail">Select an inspection record to view its report.</div>}</Section></div></PageFrame>;
}